services:
  osrm-north:
    image: osrm/osrm-backend:latest
    container_name: trek_osrm_north
    restart: unless-stopped
    ports:
      - "5001:5000"
    volumes:
      - ./osrm-data:/data
    command: osrm-routed --algorithm mld -t 1 /data/northern-zone-latest.osrm

  osrm-west:
    image: osrm/osrm-backend:latest
    container_name: trek_osrm_west
    restart: unless-stopped
    ports:
      - "5002:5000"
    volumes:
      - ./osrm-data:/data
    command: osrm-routed --algorithm mld -t 1 /data/western-zone-latest.osrm

  osrm-east:
    image: osrm/osrm-backend:latest
    container_name: trek_osrm_east
    restart: unless-stopped
    ports:
      - "5003:5000"
    volumes:
      - ./osrm-data:/data
    command: osrm-routed --algorithm mld -t 1 /data/eastern-zone-latest.osrm

  osrm-central:
    image: osrm/osrm-backend:latest
    container_name: trek_osrm_central
    restart: unless-stopped
    ports:
      - "5004:5000"
    volumes:
      - ./osrm-data:/data
    command: osrm-routed --algorithm mld -t 1 /data/central-zone-260823.osrm

  osrm-northeast:
    image: osrm/osrm-backend:latest
    container_name: trek_osrm_northeast
    restart: unless-stopped
    ports:
      - "5005:5000"
    volumes:
      - ./osrm-data:/data
    command: osrm-routed --algorithm mld -t 1 /data/north-eastern-zone-260823.osrm

  osrm-south:
    image: osrm/osrm-backend:latest
    container_name: trek_osrm_south
    restart: unless-stopped
    ports:
      - "5006:5000"
    volumes:
      - ./osrm-data:/data
    command: osrm-routed --algorithm mld -t 1 /data/southern-zone-latest.osrm
