services:
  osrm-central:
    image: osrm/osrm-backend:latest
    container_name: trek_osrm_central
    restart: unless-stopped
    ports:
      - "5004:5000"
    volumes:
      - ./osrm-data:/data
    command: osrm-routed --algorithm mld -t 1 /data/central-zone-260823.osrm
