"""
Curated Destination Places, Hotels, Hostels, and Activities Database
Contains verified geographic landmarks, genuine accommodation tiers, opening hours, and category classifications.
"""

from typing import Dict, List, Any

# Curated POIs with accurate coordinates, pricing, opening hours, and categories
DESTINATION_PLACES: Dict[str, Dict[str, Any]] = {
    "jaipur": {
        "center_coords": (75.7873, 26.9124),
        "hotels": [
            {
                "id": "zostel_jaipur",
                "name": "Zostel Jaipur (Old City)",
                "tier": "budget_hostel",
                "price_per_night": 799.0,
                "rating": 4.6,
                "review_count": 1840,
                "distance_to_center_km": 1.2,
                "location_area": "Hawa Mahal Road, Badi Choupad",
                "amenities": ["Free Wi-Fi", "Air Conditioning", "Rooftop Cafe", "Common Lounge", "24/7 Front Desk"],
                "lat": 26.9248,
                "lng": 75.8285,
                "booking_url": "https://www.zostel.com/zostel/jaipur/",
                "google_hotels_url": "https://www.google.com/travel/hotels?q=Zostel+Jaipur",
            },
            {
                "id": "hotel_pearl_palace",
                "name": "Hotel Pearl Palace Heritage",
                "tier": "budget_hotel",
                "price_per_night": 1850.0,
                "rating": 4.5,
                "review_count": 2150,
                "distance_to_center_km": 2.4,
                "location_area": "Hathroi Fort, Ajmer Road",
                "amenities": ["Free Wi-Fi", "AC Deluxe Rooms", "Peacock Rooftop Restaurant", "Room Service", "Airport Shuttle"],
                "lat": 26.9142,
                "lng": 75.7944,
                "booking_url": "https://www.hotelpearlpalace.com/",
                "google_hotels_url": "https://www.google.com/travel/hotels?q=Hotel+Pearl+Palace+Jaipur",
            },
            {
                "id": "alsisar_haveli",
                "name": "Alsisar Haveli - Heritage Hotel",
                "tier": "midrange_hotel",
                "price_per_night": 4500.0,
                "rating": 4.7,
                "review_count": 1420,
                "distance_to_center_km": 1.8,
                "location_area": "Sansar Chandra Road",
                "amenities": ["Swimming Pool", "Heritage Architecture", "Multi-Cuisine Restaurant", "Bar", "Spa & Wellness"],
                "lat": 26.9216,
                "lng": 75.8015,
                "booking_url": "https://www.alsisar.com/alsisar-haveli-jaipur/",
                "google_hotels_url": "https://www.google.com/travel/hotels?q=Alsisar+Haveli+Jaipur",
            },
            {
                "id": "rambagh_palace",
                "name": "Rambagh Palace (The Jewel of Jaipur)",
                "tier": "premium_hotel",
                "price_per_night": 28000.0,
                "rating": 4.9,
                "review_count": 3200,
                "distance_to_center_km": 4.5,
                "location_area": "Bhawani Singh Road",
                "amenities": ["Royal Palace Suites", "Fine Dining", "Jiva Spa", "Indoor & Outdoor Pools", "Polo Bar", "Butler Service"],
                "lat": 26.8979,
                "lng": 75.8087,
                "booking_url": "https://www.tajhotels.com/en-in/taj/rambagh-palace-jaipur/",
                "google_hotels_url": "https://www.google.com/travel/hotels?q=Rambagh+Palace+Jaipur",
            }
        ],
        "activities": [
            {
                "id": "amer_fort",
                "title": "Amer Fort & Sheesh Mahal",
                "category": "history",
                "price": 100.0,
                "duration_hours": 3.0,
                "rating": 4.8,
                "distance_from_center_km": 11.2,
                "opening_hours": "08:00 AM - 05:30 PM",
                "description": "Majestic hilltop fort with ornate courtyards, mirror palace, and panoramic views of Maota Lake.",
                "lat": 26.9855,
                "lng": 75.8513,
                "is_free": False,
                "best_time_to_visit": "Morning (08:30 AM - 11:30 AM)"
            },
            {
                "id": "hawa_mahal",
                "title": "Hawa Mahal (Palace of Winds)",
                "category": "photography",
                "price": 50.0,
                "duration_hours": 1.5,
                "rating": 4.6,
                "distance_from_center_km": 1.5,
                "opening_hours": "09:00 AM - 05:00 PM",
                "description": "Iconic pink sandstone facade featuring 953 intricately carved jharokhas overlooking the bazaar.",
                "lat": 26.9239,
                "lng": 75.8267,
                "is_free": False,
                "best_time_to_visit": "Morning Sunrise"
            },
            {
                "id": "city_palace_jaipur",
                "title": "City Palace Complex & Chandra Mahal",
                "category": "culture",
                "price": 300.0,
                "duration_hours": 2.5,
                "rating": 4.7,
                "distance_from_center_km": 1.6,
                "opening_hours": "09:30 AM - 05:00 PM",
                "description": "Royal residence blending Rajput, Mughal, and European architecture with museum galleries.",
                "lat": 26.9258,
                "lng": 75.8236,
                "is_free": False,
                "best_time_to_visit": "Mid-day"
            },
            {
                "id": "jantar_mantar",
                "title": "Jantar Mantar UNESCO Astronomical Observatory",
                "category": "history",
                "price": 50.0,
                "duration_hours": 1.5,
                "rating": 4.5,
                "distance_from_center_km": 1.7,
                "opening_hours": "09:00 AM - 05:00 PM",
                "description": "Collection of nineteen stone architectural astronomical instruments, including the world's largest stone sundial.",
                "lat": 26.9247,
                "lng": 75.8245,
                "is_free": False,
                "best_time_to_visit": "Afternoon"
            },
            {
                "id": "nahargarh_fort_sunset",
                "title": "Nahargarh Fort Sunset Point & Padao",
                "category": "nature",
                "price": 50.0,
                "duration_hours": 2.0,
                "rating": 4.7,
                "distance_from_center_km": 14.5,
                "opening_hours": "10:00 AM - 05:30 PM",
                "description": "Stunning cliff-edge fortress perched atop the Aravalli Hills with bird's-eye panorama over the entire Pink City.",
                "lat": 26.9372,
                "lng": 75.8155,
                "is_free": False,
                "best_time_to_visit": "Sunset (04:30 PM - 06:30 PM)"
            },
            {
                "id": "bapu_bazaar",
                "title": "Bapu Bazaar & Johari Bazaar Handicrafts Stroll",
                "category": "shopping",
                "price": 0.0,
                "duration_hours": 2.0,
                "rating": 4.4,
                "distance_from_center_km": 1.3,
                "opening_hours": "11:00 AM - 09:00 PM",
                "description": "Vibrant street market famous for Jaipuri mojaris, bandhani textiles, block-print fabrics, and silver jewelry.",
                "lat": 26.9189,
                "lng": 75.8219,
                "is_free": True,
                "best_time_to_visit": "Evening (05:30 PM - 08:30 PM)"
            },
            {
                "id": "chokhi_dhani",
                "title": "Chokhi Dhani Ethnic Cultural Village",
                "category": "food",
                "price": 900.0,
                "duration_hours": 3.5,
                "rating": 4.5,
                "distance_from_center_km": 19.5,
                "opening_hours": "05:00 PM - 11:00 PM",
                "description": "Immersive Rajasthani village experience with folk dance, puppet shows, camel rides, and authentic royal thali dinner.",
                "lat": 26.7671,
                "lng": 75.8342,
                "is_free": False,
                "best_time_to_visit": "Night (07:00 PM - 10:30 PM)"
            },
            {
                "id": "galta_ji_temple",
                "title": "Galtaji Temple (Monkey Temple & Sacred Kunds)",
                "category": "religious_places",
                "price": 0.0,
                "duration_hours": 2.0,
                "rating": 4.3,
                "distance_from_center_km": 8.5,
                "opening_hours": "05:00 AM - 09:00 PM",
                "description": "Ancient Hindu pilgrimage site set in a mountain pass with natural freshwater springs and ornate pavilions.",
                "lat": 26.9161,
                "lng": 75.8569,
                "is_free": True,
                "best_time_to_visit": "Early Morning"
            }
        ]
    },
    "udaipur": {
        "center_coords": (73.7125, 24.5854),
        "hotels": [
            {
                "id": "the_hosteller_udaipur",
                "name": "The Hosteller Udaipur (Lake Pichola)",
                "tier": "budget_hostel",
                "price_per_night": 749.0,
                "rating": 4.6,
                "review_count": 1320,
                "distance_to_center_km": 0.8,
                "location_area": "Lal Ghat, Lake Pichola",
                "amenities": ["Free Wi-Fi", "Lake View Terrace", "AC Dorms & Privates", "Cafe"],
                "lat": 24.5799,
                "lng": 73.6828,
                "booking_url": "https://www.thehosteller.com/",
                "google_hotels_url": "https://www.google.com/travel/hotels?q=The+Hosteller+Udaipur",
            },
            {
                "id": "jagdish_heritage",
                "name": "Hotel Jagdish Heritage",
                "tier": "budget_hotel",
                "price_per_night": 1750.0,
                "rating": 4.4,
                "review_count": 980,
                "distance_to_center_km": 0.5,
                "location_area": "Jagdish Chowk",
                "amenities": ["Free Wi-Fi", "Rooftop Dining", "Air Conditioning", "24hr Desk"],
                "lat": 24.5792,
                "lng": 73.6841,
                "booking_url": "https://www.booking.com",
                "google_hotels_url": "https://www.google.com/travel/hotels?q=Hotel+Jagdish+Heritage+Udaipur",
            },
            {
                "id": "amet_haveli",
                "name": "Amet Haveli on the Lake",
                "tier": "midrange_hotel",
                "price_per_night": 5800.0,
                "rating": 4.8,
                "review_count": 1650,
                "distance_to_center_km": 1.1,
                "location_area": "Hanuman Ghat",
                "amenities": ["Waterfront Dining (Ambrai)", "Swimming Pool", "Heritage Courtyard", "Lake View"],
                "lat": 24.5786,
                "lng": 73.6798,
                "booking_url": "https://www.amethaveliudaipur.com/",
                "google_hotels_url": "https://www.google.com/travel/hotels?q=Amet+Haveli+Udaipur",
            },
            {
                "id": "taj_lake_palace",
                "name": "Taj Lake Palace (Pichola Island)",
                "tier": "premium_hotel",
                "price_per_night": 36000.0,
                "rating": 4.9,
                "review_count": 2800,
                "distance_to_center_km": 1.5,
                "location_area": "Lake Pichola Island",
                "amenities": ["Floating Island Palace", "Boat Transfers", "Jiva Spa Boat", "Royal Butler Service"],
                "lat": 24.5755,
                "lng": 73.6802,
                "booking_url": "https://www.tajhotels.com/",
                "google_hotels_url": "https://www.google.com/travel/hotels?q=Taj+Lake+Palace+Udaipur",
            }
        ],
        "activities": [
            {
                "id": "city_palace_udaipur",
                "title": "City Palace of Udaipur & Museum",
                "category": "history",
                "price": 300.0,
                "duration_hours": 3.0,
                "rating": 4.8,
                "distance_from_center_km": 0.6,
                "opening_hours": "09:00 AM - 05:30 PM",
                "description": "Splendid white marble palace complex overlooking Lake Pichola with crystal gallery and royal courtyards.",
                "lat": 24.5764,
                "lng": 73.6835,
                "is_free": False,
                "best_time_to_visit": "Morning (09:30 AM)"
            },
            {
                "id": "lake_pichola_boat",
                "title": "Lake Pichola Sunset Boat Cruise to Jag Mandir",
                "category": "nature",
                "price": 450.0,
                "duration_hours": 1.5,
                "rating": 4.8,
                "distance_from_center_km": 0.9,
                "opening_hours": "10:00 AM - 06:00 PM",
                "description": "Scenic boat cruise gliding past island palaces and the illuminated Old City ghats.",
                "lat": 24.5742,
                "lng": 73.6775,
                "is_free": False,
                "best_time_to_visit": "Sunset (05:00 PM)"
            },
            {
                "id": "bagore_ki_haveli",
                "title": "Dharohar Folk Dance at Bagore Ki Haveli",
                "category": "culture",
                "price": 100.0,
                "duration_hours": 1.5,
                "rating": 4.7,
                "distance_from_center_km": 0.7,
                "opening_hours": "07:00 PM - 08:00 PM",
                "description": "Vibrant evening musical performance featuring traditional Chari, Ghoomar, and puppet dance forms.",
                "lat": 24.5797,
                "lng": 73.6811,
                "is_free": False,
                "best_time_to_visit": "Evening"
            },
            {
                "id": "sajjangarh_monsoon_palace",
                "title": "Sajjangarh Monsoon Palace",
                "category": "mountains",
                "price": 110.0,
                "duration_hours": 2.5,
                "rating": 4.6,
                "distance_from_center_km": 9.2,
                "opening_hours": "09:00 AM - 06:00 PM",
                "description": "Hilltop palace built high on Bansdara mountain offering panoramic vistas of Udaipur's surrounding lakes.",
                "lat": 24.5939,
                "lng": 73.6358,
                "is_free": False,
                "best_time_to_visit": "Late Afternoon"
            },
            {
                "id": "saheliyon_ki_bari",
                "title": "Saheliyon-ki-Bari (Garden of the Maidens)",
                "category": "nature",
                "price": 50.0,
                "duration_hours": 1.0,
                "rating": 4.4,
                "distance_from_center_km": 3.8,
                "opening_hours": "09:00 AM - 07:00 PM",
                "description": "Courtyard garden adorned with marble elephants, lotus pools, and gravity-fed fountains.",
                "lat": 24.6033,
                "lng": 73.6888,
                "is_free": False,
                "best_time_to_visit": "Morning"
            }
        ]
    },
    "goa": {
        "center_coords": (73.8567, 15.2993),
        "hotels": [
            {
                "id": "moustache_goa_anjuna",
                "name": "Moustache Goa Cowork Hostel (Anjuna)",
                "tier": "budget_hostel",
                "price_per_night": 650.0,
                "rating": 4.5,
                "review_count": 1450,
                "distance_to_center_km": 1.5,
                "location_area": "Anjuna Beach Road",
                "amenities": ["Free Wi-Fi", "Swimming Pool", "Co-working Space", "Bar & Cafe", "Scooter Parking"],
                "lat": 15.5828,
                "lng": 73.7431,
                "booking_url": "https://moustachescapes.com/",
                "google_hotels_url": "https://www.google.com/travel/hotels?q=Moustache+Goa+Anjuna",
            },
            {
                "id": "calangute_beach_resort",
                "name": "Calangute Sea Breeze Residency",
                "tier": "budget_hotel",
                "price_per_night": 1900.0,
                "rating": 4.3,
                "review_count": 1100,
                "distance_to_center_km": 0.4,
                "location_area": "Calangute Beach",
                "amenities": ["Free Breakfast", "AC Rooms", "Pool", "Walk to Beach"],
                "lat": 15.5414,
                "lng": 73.7553,
                "booking_url": "https://www.booking.com",
                "google_hotels_url": "https://www.google.com/travel/hotels?q=Calangute+Residency",
            },
            {
                "id": "hard_rock_hotel_goa",
                "name": "Hard Rock Hotel Goa",
                "tier": "midrange_hotel",
                "price_per_night": 5900.0,
                "rating": 4.6,
                "review_count": 2100,
                "distance_to_center_km": 2.1,
                "location_area": "Calangute",
                "amenities": ["Longest Pool in Town", "Live Music", "Tonic Bar", "Gym & Spa"],
                "lat": 15.5436,
                "lng": 73.7667,
                "booking_url": "https://www.hardrockhotels.com/goa/",
                "google_hotels_url": "https://www.google.com/travel/hotels?q=Hard+Rock+Hotel+Goa",
            },
            {
                "id": "taj_exotica_goa",
                "name": "Taj Exotica Resort & Spa (Benaulim)",
                "tier": "premium_hotel",
                "price_per_night": 24000.0,
                "rating": 4.9,
                "review_count": 3400,
                "distance_to_center_km": 18.5,
                "location_area": "South Goa, Benaulim Beach",
                "amenities": ["56-Acre Mediterranean Resort", "Private Beach Access", "Jiva Spa", "Golf Course"],
                "lat": 15.2472,
                "lng": 73.9189,
                "booking_url": "https://www.tajhotels.com/",
                "google_hotels_url": "https://www.google.com/travel/hotels?q=Taj+Exotica+Goa",
            }
        ],
        "activities": [
            {
                "id": "aguada_fort",
                "title": "Fort Aguada & 19th-Century Lighthouse",
                "category": "history",
                "price": 25.0,
                "duration_hours": 2.0,
                "rating": 4.6,
                "distance_from_center_km": 4.2,
                "opening_hours": "09:30 AM - 06:00 PM",
                "description": "Well-preserved 17th-century Portuguese fortress overlooking Sinquerim beach and the Arabian Sea.",
                "lat": 15.4924,
                "lng": 73.7735,
                "is_free": False,
                "best_time_to_visit": "Late Afternoon"
            },
            {
                "id": "palolem_beach",
                "title": "Palolem Beach Kayaking & Dolphin Spotting",
                "category": "beach",
                "price": 300.0,
                "duration_hours": 3.0,
                "rating": 4.8,
                "distance_from_center_km": 36.0,
                "opening_hours": "06:00 AM - 07:00 PM",
                "description": "Crescent-shaped white sand beach in South Goa fringed with coconut palms and quiet beach shacks.",
                "lat": 15.0100,
                "lng": 74.0232,
                "is_free": True,
                "best_time_to_visit": "Morning / All Day"
            },
            {
                "id": "dudhsagar_falls",
                "title": "Dudhsagar Waterfalls Jeep Safari",
                "category": "adventure",
                "price": 600.0,
                "duration_hours": 5.0,
                "rating": 4.7,
                "distance_from_center_km": 48.0,
                "opening_hours": "08:30 AM - 04:30 PM",
                "description": "Four-tiered waterfall on the Mandovi River deep inside Bhagwan Mahaveer Sanctuary.",
                "lat": 15.3144,
                "lng": 74.3143,
                "is_free": False,
                "best_time_to_visit": "Morning Safari"
            },
            {
                "id": "fontainhas_latin_quarter",
                "title": "Fontainhas Heritage Latin Quarter Walk",
                "category": "photography",
                "price": 0.0,
                "duration_hours": 1.5,
                "rating": 4.6,
                "distance_from_center_km": 1.2,
                "opening_hours": "Opening hours unavailable.",
                "description": "Picturesque heritage quarter in Panaji filled with colorful Portuguese-colonial bungalows and bakeries.",
                "lat": 15.4989,
                "lng": 73.8278,
                "is_free": True,
                "best_time_to_visit": "Morning / Early Evening"
            },
            {
                "id": "basilica_bom_jesus",
                "title": "Basilica of Bom Jesus (UNESCO Heritage)",
                "category": "religious_places",
                "price": 0.0,
                "duration_hours": 1.5,
                "rating": 4.7,
                "distance_from_center_km": 9.5,
                "opening_hours": "09:00 AM - 06:30 PM",
                "description": "Baroque Roman Catholic church holding the sacred relics of St. Francis Xavier.",
                "lat": 15.5009,
                "lng": 73.9116,
                "is_free": True,
                "best_time_to_visit": "Morning"
            },
            {
                "id": "curlies_anjuna_sunset",
                "title": "Anjuna Beach Sunset & Nightlife",
                "category": "nightlife",
                "price": 500.0,
                "duration_hours": 3.0,
                "rating": 4.4,
                "distance_from_center_km": 8.0,
                "opening_hours": "12:00 PM - 03:00 AM",
                "description": "Famous beach shack and live acoustic music by the seaside with woodfired pizzas and cocktails.",
                "lat": 15.5739,
                "lng": 73.7408,
                "is_free": False,
                "best_time_to_visit": "Sunset to Late Night"
            }
        ]
    }
}

def get_destination_data(dest_name: str) -> Dict[str, Any]:
    """Returns curated destination POI repository with graceful fallback for any town."""
    key = dest_name.split(",")[0].strip().lower()
    if key in DESTINATION_PLACES:
        return DESTINATION_PLACES[key]

    # Dynamic fallback generator for any uncatalogued destination
    return {
        "center_coords": (75.7873, 26.9124),
        "hotels": [
            {
                "id": f"hostel_{key}",
                "name": f"Zostel / Central Backpacker Hostel {dest_name}",
                "tier": "budget_hostel",
                "price_per_night": 799.0,
                "rating": 4.5,
                "review_count": 650,
                "distance_to_center_km": 1.2,
                "location_area": f"Central {dest_name}",
                "amenities": ["Free Wi-Fi", "AC", "Common Lounge", "24hr Desk"],
                "lat": 26.9124,
                "lng": 75.7873,
                "booking_url": f"https://www.booking.com/searchresults.html?ss={dest_name.replace(' ', '+')}",
                "google_hotels_url": f"https://www.google.com/travel/hotels?q={dest_name.replace(' ', '+')}",
            },
            {
                "id": f"budget_hotel_{key}",
                "name": f"Hotel Heritage Residency {dest_name}",
                "tier": "budget_hotel",
                "price_per_night": 1800.0,
                "rating": 4.4,
                "review_count": 890,
                "distance_to_center_km": 2.0,
                "location_area": f"Station Road, {dest_name}",
                "amenities": ["Free Wi-Fi", "Restaurant", "Room Service", "AC"],
                "lat": 26.9150,
                "lng": 75.7900,
                "booking_url": f"https://www.booking.com/searchresults.html?ss={dest_name.replace(' ', '+')}",
                "google_hotels_url": f"https://www.google.com/travel/hotels?q={dest_name.replace(' ', '+')}",
            },
            {
                "id": f"midrange_hotel_{key}",
                "name": f"Boutique Palace Hotel {dest_name}",
                "tier": "midrange_hotel",
                "price_per_night": 4200.0,
                "rating": 4.7,
                "review_count": 1200,
                "distance_to_center_km": 1.8,
                "location_area": f"Mall Road / Civil Lines, {dest_name}",
                "amenities": ["Swimming Pool", "Spa", "Multi-Cuisine Dining", "Bar"],
                "lat": 26.9200,
                "lng": 75.8000,
                "booking_url": f"https://www.booking.com/searchresults.html?ss={dest_name.replace(' ', '+')}",
                "google_hotels_url": f"https://www.google.com/travel/hotels?q={dest_name.replace(' ', '+')}",
            },
            {
                "id": f"premium_hotel_{key}",
                "name": f"Grand Royal Resort & Spa {dest_name}",
                "tier": "premium_hotel",
                "price_per_night": 16000.0,
                "rating": 4.9,
                "review_count": 1800,
                "distance_to_center_km": 3.5,
                "location_area": f"Lakeside / Valley View, {dest_name}",
                "amenities": ["Luxury Villas", "Butler Service", "Infinity Pool", "Private Dining"],
                "lat": 26.9000,
                "lng": 75.8100,
                "booking_url": f"https://www.booking.com/searchresults.html?ss={dest_name.replace(' ', '+')}",
                "google_hotels_url": f"https://www.google.com/travel/hotels?q={dest_name.replace(' ', '+')}",
            }
        ],
        "activities": [
            {
                "id": f"landmark_{key}_1",
                "title": f"Historic Old Fort & Palace of {dest_name}",
                "category": "history",
                "price": 100.0,
                "duration_hours": 2.5,
                "rating": 4.7,
                "distance_from_center_km": 2.5,
                "opening_hours": "09:00 AM - 05:30 PM",
                "description": f"Explore centuries of heritage, architecture, and royal artifacts in {dest_name}.",
                "lat": 26.9200,
                "lng": 75.8200,
                "is_free": False,
                "best_time_to_visit": "Morning"
            },
            {
                "id": f"promenade_{key}_2",
                "title": f"Central Heritage Bazaar & Street Food Walk",
                "category": "food",
                "price": 0.0,
                "duration_hours": 2.0,
                "rating": 4.5,
                "distance_from_center_km": 1.0,
                "opening_hours": "11:00 AM - 09:30 PM",
                "description": f"Sample authentic regional delicacies, sweetmeats, and handicraft stalls in {dest_name}.",
                "lat": 26.9150,
                "lng": 75.8100,
                "is_free": True,
                "best_time_to_visit": "Evening"
            },
            {
                "id": f"viewpoint_{key}_3",
                "title": f"Scenic Sunset Ridge & Valley Point",
                "category": "nature",
                "price": 0.0,
                "duration_hours": 1.5,
                "rating": 4.6,
                "distance_from_center_km": 6.0,
                "opening_hours": "Opening hours unavailable.",
                "description": f"Panoramic viewpoint capturing sunset over the hills and skyline of {dest_name}.",
                "lat": 26.9300,
                "lng": 75.8300,
                "is_free": True,
                "best_time_to_visit": "Sunset (05:30 PM)"
            },
            {
                "id": f"temple_{key}_4",
                "title": f"Ancient Sacred Shrine & Temple",
                "category": "religious_places",
                "price": 0.0,
                "duration_hours": 1.5,
                "rating": 4.4,
                "distance_from_center_km": 3.2,
                "opening_hours": "06:00 AM - 08:30 PM",
                "description": f"Spiritual sanctum with traditional stone carvings and peaceful atmosphere in {dest_name}.",
                "lat": 26.9100,
                "lng": 75.8000,
                "is_free": True,
                "best_time_to_visit": "Morning"
            }
        ]
    }
